FROM python:3.12-slim
WORKDIR /app
COPY requirements.txt pip.conf ./
ENV PIP_CONFIG_FILE=/app/pip.conf
RUN pip install --no-cache-dir -r requirements.txt
COPY . .
CMD ["uvicorn", "main:app", "--host", "0.0.0.0", "--port", "8000", "--reload"]
